apiVersion: v1
kind: Pod
metadata:
  name: gateway-app
  namespace: {{ .Values.namespace }}
  labels:
    app: gateway-app-{{ .Values.namespace }}
spec:
  containers:
    - name: gateway-app
      image: {{ .Values.gateway.image }}:{{ .Values.gateway.tag }}
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh" ]
      args: [ "-c", "uvicorn main:app --reload --host 0.0.0.0" ]
      ports:
        - containerPort: 8000
      env:
        - name: USERS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: uri-apis-{{ .Values.namespace }}
              key: USERS_SERVICE_URL
        - name: ORDERS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: uri-apis-{{ .Values.namespace }}
              key: ORDERS_SERVICE_URL

