apiVersion: v1
kind: Service
metadata:
  name: orders-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  labels:
    name: orders-{{ .Values.namespace }}
spec:
  selector:
    app: orders-app
  type: ClusterIP
  ports:
    - name: orders
      protocol: TCP
      port: 8000
      targetPort: 8000


